# KEY VALUE
uint8 KEY_FEEDBACK_KEY_1 = 1
uint8 KEY_FEEDBACK_KEY_2 = 2
uint8 KEY_FEEDBACK_KEY_3 = 3
uint8 KEY_FEEDBACK_KEY_4 = 4
uint8 KEY_FEEDBACK_KEY_5 = 5
uint8 KEY_FEEDBACK_KEY_6 = 6
uint8 KEY_FEEDBACK_KEY_7 = 7
uint8 KEY_FEEDBACK_KEY_8 = 8
uint8 KEY_FEEDBACK_KEY_9 = 9
uint8 KEY_DISPLAY_MODE = 99
uint8 KEY_LEFT_MOTOR_INTENSITY  = 10
uint8 KEY_RIGHT_MOTOR_INTENSITY = 11
uint8 KEY_BOTH_MOTOR_INTENSITY  = 12

uint8 VALUE_DISPLAY_MODE_STANDARD    = 0
uint8 VALUE_DISPLAY_MODE_CUSTOM_TEXT = 1
uint8 VALUE_DISPLAY_MODE_TEXT_VALUE  = 2
uint8 VALUE_DISPLAY_MODE_VALUES      = 3

uint8 VALUE_MOTOR_INTENSITY_OFF  = 0
uint8 VALUE_MOTOR_INTENSITY_HIGH = 1
uint8 VALUE_MOTOR_INTENSITY_MAX  = 2

uint8 Key
int32 Value
---
